import LocalizedStrings from 'react-native-localization';

const strings = new LocalizedStrings({
  en: {
    welcome: "WaterSave",
    slogan: "Every Drop Matters",
    email: "Email",
    password: "Password",
    login: "Login",
    forgotPassword: "Forgot Password?",
    surveyIntro: "Welcome to WaterSave!",
    surveyDescription: "Before we start, we'll ask you a few questions about your water usage habits. This will help us personalize your water-saving journey.",
    startSurvey: "Start Survey",
    continue: "Continue",
    cardOne: "Complete the Water Usage Survey",
    cardTwo: "Get Personalized Water-Saving Tasks",
    cardThree: "Track Your Progress & Save Water",
    questionProgress: "Question %d of %d",
    surveyComplete: "Survey Complete!",
    potentialSaving: "Potential Water Saving",
    currentUsage: "Current Water Usage",
    achievements: "Your Achievements",
    tasks: "Recommended Tasks",
    startJourney: "Start Your Water-Saving Journey",
    formatString: function(str, ...args) {
      return str.replace(/%[sd]/g, function() {
        return args.shift() || '';
      });
    },
    waterSavingPotential: "You can save up to %d% of your water usage!",
    improvementArea: "Improvement Areas - %s",
    readyForChallenge: "Ready for the Challenge?",
    challengeDescription: "Start your water-saving journey now! Complete tasks in your improvement areas and track your progress daily.",
    startChallenge: "Start 30-Day Water Challenge",
    challengeTitle: "30-Day Water Challenge",
    categoryProgress: "Progress in %s",
    dailyTasks: "Today's Tasks",
    recentAchievements: "Recent Improvements",
    watchTutorial: "Watch Tutorial",
    needsImprovement: "Needs Improvement",
    improvedAnswer: "Great Improvement!",
    savedWater: "Saved %dL of water",
    closeVideo: "Close",
    learnMore: "Learn More",
    readMore: "Read Article",
    close: "Close",
    error: "Error",
    videoLoadError: "Could not load the video. Please try again later.",
    totalSavings: "Total Water Savings",
    savingEquivalent: "Equivalent to %s of household usage",
    progressOverTime: "Progress Over Time",
    completedChallenges: "Completed Challenges",
    activeChallenges: "Active Challenges",
    successRate: "Success Rate",
    keepGoing: "Keep Going!",
    motivationMessage: "You're making a real difference! Every drop you save helps our planet.",
    challenges: "Challenges",
    achievements: "Achievements",
    profile: "Profile",
    taskCompleted: "Task Completed!",
    taskCompletedMessage: "Great job! Keep up the good work!",
    remainingTasks: "%d tasks remaining",
    improvementTips: "Improvement Tips & Resources",
    restartChallenge: "Restart Challenge",
    restartChallengeConfirm: "Are you sure you want to restart the challenge? Your current progress will be saved in history.",
    cancel: "Cancel",
    confirm: "Confirm",
    unlockedBadges: "Unlocked Badges",
    totalWaterSaved: "Total Water Saved",
    recentAchievements: "Recent Achievements",
    categoryCompleted: "Category Completed",
    categoryCompletedMessage: "You've completed all tasks in %s category!",
    watchedTutorial: "Watched a tutorial video",
    readArticle: "Read an informative article",
    learningProgress: "Learning Progress",
    watchedVideos: "Videos Watched",
    readArticles: "Articles Read",
    keepLearning: "Keep Learning!",
    keepLearningMessage: "Watch the tutorial or read more to improve your water-saving knowledge!",
    challengeLimit: "Active Challenges: %d/%d",
    noProgressData: "Complete challenges to see your progress over time",
    resetData: "Reset All Data (Debug)",
    resetDataConfirm: "This will delete all your data. Are you sure?",
    signOut: "Sign Out",
    signOutConfirm: "Are you sure you want to sign out?",
    introTitle1: "Save Water, Save Life",
    introDesc1: "Join us in making a difference! Learn how small changes in your daily water usage can have a big impact on our planet.",
    
    introTitle2: "Personalized Journey",
    introDesc2: "Take a quick survey to get customized water-saving recommendations based on your habits and lifestyle.",
    
    introTitle3: "Track & Improve",
    introDesc3: "Monitor your progress, earn achievements, and see the real impact of your water-saving efforts.",
    
    skip: "Skip",
    next: "Next",
    getStarted: "Get Started",
  },
  tr: {
    welcome: "WaterSave",
    slogan: "Her Damla Değerlidir",
    email: "E-posta",
    password: "Şifre",
    login: "Giriş Yap",
    forgotPassword: "Şifremi Unuttum",
    surveyIntro: "WaterSave'e Hoş Geldiniz!",
    surveyDescription: "Başlamadan önce, su kullanım alışkanlıklarınız hakkında birkaç soru soracağız. Bu, su tasarrufu yolculuğunuzu kişiselleştirmemize yardımcı olacak.",
    startSurvey: "Ankete Başla",
    continue: "Devam Et",
    cardOne: "Su Kullanım Anketini Tamamla",
    cardTwo: "Kişiselleştirilmiş Su Tasarrufu Görevlerini Al",
    cardThree: "İlerlemeni Takip Et & Su Tasarrufu Yap",
    questionProgress: "Soru %d / %d",
    surveyComplete: "Anket Tamamlandı!",
    potentialSaving: "Potansiyel Su Tasarrufu",
    currentUsage: "Mevcut Su Kullanımı",
    achievements: "Başarılarınız",
    tasks: "Önerilen Görevler",
    startJourney: "Su Tasarrufu Yolculuğuna Başla",
    formatString: function(str, ...args) {
      return str.replace(/%[sd]/g, function() {
        return args.shift() || '';
      });
    },
    waterSavingPotential: "Su kullanımınızın %d% kadarını tasarruf edebilirsiniz!",
    improvementArea: "%s Alanında İyileştirmeler",
    readyForChallenge: "Meydan Okumaya Hazır mısınız?",
    challengeDescription: "Su tasarrufu yolculuğunuza şimdi başlayın! İyileştirme alanlarınızdaki görevleri tamamlayın ve günlük ilerlemenizi takip edin.",
    startChallenge: "30 Günlük Su Tasarrufu Meydan Okumasını Başlat",
    challengeTitle: "30 Günlük Su Tasarrufu",
    categoryProgress: "%s Alanında İlerleme",
    dailyTasks: "Bugünün Görevleri",
    recentAchievements: "Son İyileştirmeler",
    watchTutorial: "Eğitimi İzle",
    needsImprovement: "İyileştirme Gerekli",
    improvedAnswer: "Harika İyileştirme!",
    savedWater: "%dL su tasarrufu sağlandı",
    closeVideo: "Kapat",
    learnMore: "Daha Fazla Bilgi",
    readMore: "Makaleyi Oku",
    close: "Kapat",
    error: "Hata",
    videoLoadError: "Video yüklenemedi. Lütfen daha sonra tekrar deneyin.",
    totalSavings: "Toplam Su Tasarrufu",
    savingEquivalent: "Ev kullanımının %s'sine eşdeğer",
    progressOverTime: "Zaman İçindeki İlerleme",
    completedChallenges: "Tamamlanan Görevler",
    activeChallenges: "Aktif Görevler",
    successRate: "Başarı Oranı",
    keepGoing: "Devam Et!",
    motivationMessage: "Gerçek bir fark yaratıyorsun! Tasarruf ettiğin her damla gezegenimize yardımcı oluyor.",
    challenges: "Görevler",
    achievements: "Başarılar",
    profile: "Profil",
    taskCompleted: "Görev Tamamlandı!",
    taskCompletedMessage: "Harika iş! Böyle devam et!",
    remainingTasks: "%d görev kaldı",
    improvementTips: "İyileştirme İpuçları & Kaynaklar",
    restartChallenge: "Görevi Yeniden Başlat",
    restartChallengeConfirm: "Görevi yeniden başlatmak istediğinizden emin misiniz? Mevcut ilerlemeniz geçmişe kaydedilecek.",
    cancel: "İptal",
    confirm: "Onayla",
    unlockedBadges: "Kazanılan Rozetler",
    totalWaterSaved: "Toplam Su Tasarrufu",
    recentAchievements: "Son Başarılar",
    categoryCompleted: "Kategori Tamamlandı",
    categoryCompletedMessage: "%s kategorisindeki tüm görevleri tamamladınız!",
    watchedTutorial: "Eğitim videosu izlendi",
    readArticle: "Bilgilendirici makale okundu",
    learningProgress: "Öğrenme İlerlemesi",
    watchedVideos: "İzlenen Videolar",
    readArticles: "Okunan Makaleler",
    keepLearning: "Öğrenmeye Devam Et!",
    keepLearningMessage: "Su tasarrufu bilgini artırmak için eğitim videosunu izle veya daha fazla bilgi edin!",
    challengeLimit: "Aktif Görevler: %d/%d",
    noProgressData: "İlerleme grafiğini görmek için görevleri tamamlayın",
    resetData: "Tüm Verileri Sıfırla (Debug)",
    resetDataConfirm: "Tüm verileriniz silinecek. Emin misiniz?",
    signOut: "Çıkış Yap",
    signOutConfirm: "Çıkış yapmak istediğinizden emin misiniz?",
    introTitle1: "Suyu Koru, Hayatı Koru",
    introDesc1: "Fark yaratmaya katılın! Günlük su kullanımınızdaki küçük değişikliklerin gezegenimiz üzerinde nasıl büyük bir etki yaratabileceğini öğrenin.",
    
    introTitle2: "Kişiselleştirilmiş Yolculuk",
    introDesc2: "Alışkanlıklarınıza ve yaşam tarzınıza göre özelleştirilmiş su tasarrufu önerileri almak için kısa bir ankete katılın.",
    
    introTitle3: "Takip Et & Geliştir",
    introDesc3: "İlerlemenizi izleyin, başarılar kazanın ve su tasarrufu çabalarınızın gerçek etkisini görün.",
    
    skip: "Atla",
    next: "İleri",
    getStarted: "Başla",
  }
});

try {
  strings.setLanguage('en');
} catch (error) {
  console.warn('Language setting error:', error);
}

export default strings; 